import { TerraformConfig, TerraformResource } from "tfs";
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterbool {
  value: boolean;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterdouble {
  value: number;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterenum {
  value: string;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterEnumList {
  value: string[];
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterint {
  value: number;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterIntList {
  value: number[];
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterstring {
  value: string;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterStringList {
  value: string[];
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameter {
  name: string;
  value_type: string;
  bool: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterbool;
  double: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterdouble;
  enum: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterenum;
  enum_list: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterEnumList;
  int: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterint;
  int_list: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterIntList;
  string: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterstring;
  string_list: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameterStringList;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameter {
  security_control_id: string;
  parameter: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameterparameter;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfiguration {
  disabled_control_identifiers?: string[];
  enabled_control_identifiers?: string[];
  security_control_custom_parameter: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfigurationSecurityControlCustomParameter;
}
export interface AwsSecurityhubConfigurationPolicyArgsConfigurationPolicy {
  enabled_standard_arns?: string[];
  service_enabled: boolean;
  security_controls_configuration: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicySecurityControlsConfiguration;
}
export interface AwsSecurityhubConfigurationPolicyArgs {
  description?: string;
  name: string;
  configuration_policy: AwsSecurityhubConfigurationPolicyArgsConfigurationPolicy;
}
export class aws_securityhub_configuration_policy extends TerraformResource {
  readonly arn!: string;
  readonly id?: string;
  constructor(config: TerraformConfig, resourceName: string, args: AwsSecurityhubConfigurationPolicyArgs) {
    super(config, "resource", args, resourceName, "aws_securityhub_configuration_policy");
  }
}