import { TerraformConfig, TerraformResource } from "tfs";
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStatmetricdimensions {
  name: string;
  value: string;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStatmetric {
  metric_name: string;
  namespace: string;
  dimensions: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStatmetricdimensions;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStat {
  stat: string;
  unit?: string;
  metric: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStatmetric;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueries {
  expression?: string;
  id: string;
  label?: string;
  return_data?: boolean;
  metric_stat: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStat;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecification {
  metric_data_queries: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueries;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStatmetricdimensions {
  name: string;
  value: string;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStatmetric {
  metric_name: string;
  namespace: string;
  dimensions: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStatmetricdimensions;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStat {
  stat: string;
  unit?: string;
  metric: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStatmetric;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueries {
  expression?: string;
  id: string;
  label?: string;
  return_data?: boolean;
  metric_stat: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStat;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecification {
  metric_data_queries: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueries;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStatmetricdimensions {
  name: string;
  value: string;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStatmetric {
  metric_name: string;
  namespace: string;
  dimensions: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStatmetricdimensions;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStat {
  stat: string;
  unit?: string;
  metric: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStatmetric;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueries {
  expression?: string;
  id: string;
  label?: string;
  return_data?: boolean;
  metric_stat: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStat;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecification {
  metric_data_queries: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueries;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecification {
  predefined_metric_type: string;
  resource_label?: string;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecification {
  predefined_metric_type: string;
  resource_label?: string;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecification {
  predefined_metric_type: string;
  resource_label?: string;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecification {
  target_value: number;
  customized_capacity_metric_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecification;
  customized_load_metric_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecification;
  customized_scaling_metric_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecification;
  predefined_load_metric_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecification;
  predefined_metric_pair_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecification;
  predefined_scaling_metric_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecification;
}
export interface AwsAutoscalingPolicyArgsPredictiveScalingConfiguration {
  max_capacity_breach_behavior?: string;
  max_capacity_buffer?: string;
  mode?: string;
  scheduling_buffer_time?: string;
  metric_specification: AwsAutoscalingPolicyArgsPredictiveScalingConfigurationMetricSpecification;
}
export interface AwsAutoscalingPolicyArgsStepAdjustment {
  metric_interval_lower_bound?: string;
  metric_interval_upper_bound?: string;
  scaling_adjustment: number;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension {
  name: string;
  value: string;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetricsMetricStatmetricdimensions {
  name: string;
  value: string;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetricsMetricStatmetric {
  metric_name: string;
  namespace: string;
  dimensions: AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetricsMetricStatmetricdimensions;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetricsMetricStat {
  stat: string;
  unit?: string;
  metric: AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetricsMetricStatmetric;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetrics {
  expression?: string;
  id: string;
  label?: string;
  return_data?: boolean;
  metric_stat: AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetricsMetricStat;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecification {
  metric_name?: string;
  namespace?: string;
  statistic?: string;
  unit?: string;
  metric_dimension: AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension;
  metrics: AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecificationmetrics;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfigurationPredefinedMetricSpecification {
  predefined_metric_type: string;
  resource_label?: string;
}
export interface AwsAutoscalingPolicyArgsTargetTrackingConfiguration {
  disable_scale_in?: boolean;
  target_value: number;
  customized_metric_specification: AwsAutoscalingPolicyArgsTargetTrackingConfigurationCustomizedMetricSpecification;
  predefined_metric_specification: AwsAutoscalingPolicyArgsTargetTrackingConfigurationPredefinedMetricSpecification;
}
export interface AwsAutoscalingPolicyArgs {
  adjustment_type?: string;
  autoscaling_group_name: string;
  cooldown?: number;
  enabled?: boolean;
  estimated_instance_warmup?: number;
  min_adjustment_magnitude?: number;
  name: string;
  policy_type?: string;
  scaling_adjustment?: number;
  predictive_scaling_configuration: AwsAutoscalingPolicyArgsPredictiveScalingConfiguration;
  step_adjustment: AwsAutoscalingPolicyArgsStepAdjustment;
  target_tracking_configuration: AwsAutoscalingPolicyArgsTargetTrackingConfiguration;
}
export class aws_autoscaling_policy extends TerraformResource {
  readonly arn!: string;
  readonly id?: string;
  readonly metric_aggregation_type?: string;
  constructor(config: TerraformConfig, resourceName: string, args: AwsAutoscalingPolicyArgs) {
    super(config, "resource", args, resourceName, "aws_autoscaling_policy");
  }
}