import { TerraformConfig, TerraformResource } from "tfs";
export interface AwsLexv2modelsSlotArgsMultipleValuesSetting {
  allow_multiple_values?: boolean;
}
export interface AwsLexv2modelsSlotArgsObfuscationSetting {
  obfuscation_setting_type: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecificationDefaultValueList {
  default_value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecification {
  default_value_list: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecificationDefaultValueList;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroup {
  message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes {
  allow_audio_input: boolean;
  allow_dtmf_input: boolean;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification {
  end_timeout_ms: number;
  max_length_ms: number;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification {
  deletion_character: string;
  end_character: string;
  end_timeout_ms: number;
  max_length: number;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification {
  start_timeout_ms: number;
  audio_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification;
  dtmf_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification {
  start_timeout_ms: number;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecification {
  allow_interrupt?: boolean;
  map_block_key: string;
  allowed_input_types: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes;
  audio_and_dtmf_input_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification;
  text_input_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecification {
  allow_interrupt?: boolean;
  max_retries: number;
  message_selection_strategy?: string;
  message_group: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroup;
  prompt_attempts_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecification;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingSampleUtterance {
  utterance: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup {
  message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponse {
  allow_interrupt?: boolean;
  message_group: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup {
  message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse {
  allow_interrupt?: boolean;
  frequency_in_seconds: number;
  timeout_in_seconds: number;
  message_group: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup {
  message: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponse {
  allow_interrupt?: boolean;
  message_group: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecification {
  active?: boolean;
  continue_response: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponse;
  still_waiting_response: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse;
  waiting_response: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponse;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSetting {
  default_value_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecification;
  prompt_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecification;
  sample_utterance: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingSampleUtterance;
  wait_and_continue_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecification;
}
export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecification {
  map_block_key: string;
  slot_type_id: string;
  value_elicitation_setting: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSetting;
}
export interface AwsLexv2modelsSlotArgsSubSlotSetting {
  expression?: string;
  slot_specification: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecification;
}
export interface AwsLexv2modelsSlotArgstimeouts {
  create?: string;
  delete?: string;
  update?: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecificationDefaultValueList {
  default_value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecification {
  default_value_list: AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecificationDefaultValueList;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroup {
  message: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes {
  allow_audio_input: boolean;
  allow_dtmf_input: boolean;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification {
  end_timeout_ms: number;
  max_length_ms: number;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification {
  deletion_character: string;
  end_character: string;
  end_timeout_ms: number;
  max_length: number;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification {
  start_timeout_ms: number;
  audio_specification: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification;
  dtmf_specification: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification {
  start_timeout_ms: number;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecification {
  allow_interrupt?: boolean;
  map_block_key: string;
  allowed_input_types: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes;
  audio_and_dtmf_input_specification: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification;
  text_input_specification: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecification {
  allow_interrupt?: boolean;
  max_retries: number;
  message_selection_strategy?: string;
  message_group: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroup;
  prompt_attempts_specification: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecification;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingSampleUtterance {
  utterance: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingSlotResolutionSetting {
  slot_resolution_strategy: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup {
  message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponse {
  allow_interrupt?: boolean;
  message_group: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup {
  message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse {
  allow_interrupt?: boolean;
  frequency_in_seconds: number;
  timeout_in_seconds: number;
  message_group: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessagePlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessage {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessagePlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessageSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationCustomPayload {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCardbutton {
  text: string;
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCardbutton;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationPlainTextMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationSsmlMessage {
  value: string;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariation {
  custom_payload: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationCustomPayload;
  image_response_card: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationImageResponseCard;
  plain_text_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationPlainTextMessage;
  ssml_message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariationSsmlMessage;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup {
  message: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupmessage;
  variation: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupvariation;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponse {
  allow_interrupt?: boolean;
  message_group: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecification {
  active?: boolean;
  continue_response: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponse;
  still_waiting_response: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse;
  waiting_response: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponse;
}
export interface AwsLexv2modelsSlotArgsValueElicitationSetting {
  slot_constraint: string;
  default_value_specification: AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecification;
  prompt_specification: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecification;
  sample_utterance: AwsLexv2modelsSlotArgsValueElicitationSettingSampleUtterance;
  slot_resolution_setting: AwsLexv2modelsSlotArgsValueElicitationSettingSlotResolutionSetting;
  wait_and_continue_specification: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecification;
}
export interface AwsLexv2modelsSlotArgs {
  bot_id: string;
  bot_version: string;
  description?: string;
  intent_id: string;
  locale_id: string;
  name: string;
  multiple_values_setting: AwsLexv2modelsSlotArgsMultipleValuesSetting;
  obfuscation_setting: AwsLexv2modelsSlotArgsObfuscationSetting;
  sub_slot_setting: AwsLexv2modelsSlotArgsSubSlotSetting;
  timeouts: AwsLexv2modelsSlotArgstimeouts;
  value_elicitation_setting: AwsLexv2modelsSlotArgsValueElicitationSetting;
}
export class aws_lexv2models_slot extends TerraformResource {
  readonly id!: string;
  readonly slot_id!: string;
  readonly slot_type_id?: string;
  constructor(config: TerraformConfig, resourceName: string, args: AwsLexv2modelsSlotArgs) {
    super(config, "resource", args, resourceName, "aws_lexv2models_slot");
  }
}