import { TerraformConfig, TerraformResource } from "tfs";
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentifyTransformationConfig {
  deidentify_template?: string;
  image_redact_template?: string;
  structured_deidentify_template?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentifyTransformationDetailsStorageConfigtable {
  dataset_id: string;
  project_id: string;
  table_id?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentifyTransformationDetailsStorageConfig {
  table: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentifyTransformationDetailsStorageConfigtable;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentify {
  cloud_storage_output: string;
  file_types_to_transform?: string[];
  transformation_config: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentifyTransformationConfig;
  transformation_details_storage_config: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentifyTransformationDetailsStorageConfig;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsJobNotificationEmails {}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPubSub {
  topic: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPublishFindingsToCloudDataCatalog {}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPublishSummaryToCscc {}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPublishToStackdriver {}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsSaveFindingsOutputConfigtable {
  dataset_id: string;
  project_id: string;
  table_id?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsSaveFindingsOutputConfig {
  output_schema?: string;
  table: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsSaveFindingsOutputConfigtable;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactionsSaveFindings {
  output_config: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsSaveFindingsOutputConfig;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobactions {
  deidentify: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsdeidentify;
  job_notification_emails: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsJobNotificationEmails;
  pub_sub: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPubSub;
  publish_findings_to_cloud_data_catalog: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPublishFindingsToCloudDataCatalog;
  publish_summary_to_cscc: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPublishSummaryToCscc;
  publish_to_stackdriver: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsPublishToStackdriver;
  save_findings: GoogleDataLossPreventionJobTriggerArgsInspectJobactionsSaveFindings;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesdictionaryCloudStoragePath {
  path: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesdictionaryWordList {
  words: string[];
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesdictionary {
  cloud_storage_path: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesdictionaryCloudStoragePath;
  word_list: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesdictionaryWordList;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesInfoType {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesregex {
  group_indexes?: number[];
  pattern: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesStoredType {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesSurrogateType {}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypes {
  exclusion_type?: string;
  likelihood?: string;
  dictionary: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesdictionary;
  info_type: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesInfoType;
  regex: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesregex;
  sensitivity_score: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesSensitivityScore;
  stored_type: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesStoredType;
  surrogate_type: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypesSurrogateType;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimitsMaxFindingsPerInfoTypeInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimitsMaxFindingsPerInfoTypeInfoType {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimitsMaxFindingsPerInfoTypeInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimitsMaxFindingsPerInfoType {
  max_findings?: number;
  info_type: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimitsMaxFindingsPerInfoTypeInfoType;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimits {
  max_findings_per_item?: number;
  max_findings_per_request?: number;
  max_findings_per_info_type: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimitsMaxFindingsPerInfoType;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuledictionaryCloudStoragePath {
  path: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuledictionaryWordList {
  words: string[];
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuledictionary {
  cloud_storage_path: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuledictionaryCloudStoragePath;
  word_list: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuledictionaryWordList;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordHotwordRegex {
  group_indexes?: number[];
  pattern?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordproximity {
  window_after?: number;
  window_before?: number;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeByHotword {
  hotword_regex: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordHotwordRegex;
  proximity: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordproximity;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypes {
  info_types: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypes;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleregex {
  group_indexes?: number[];
  pattern: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRule {
  matching_type: string;
  dictionary: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuledictionary;
  exclude_by_hotword: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeByHotword;
  exclude_info_types: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypes;
  regex: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRuleregex;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRuleHotwordRegex {
  group_indexes?: number[];
  pattern?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRuleLikelihoodAdjustment {
  fixed_likelihood?: string;
  relative_likelihood?: number;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRuleproximity {
  window_after?: number;
  window_before?: number;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRule {
  hotword_regex: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRuleHotwordRegex;
  likelihood_adjustment: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRuleLikelihoodAdjustment;
  proximity: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRuleproximity;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrules {
  exclusion_rule: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesExclusionRule;
  hotword_rule: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrulesHotwordRule;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSet {
  info_types: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetInfoTypes;
  rules: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSetrules;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfig {
  exclude_info_types?: boolean;
  include_quote?: boolean;
  min_likelihood?: string;
  custom_info_types: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigCustomInfoTypes;
  info_types: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigInfoTypes;
  limits: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfiglimits;
  rule_set: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfigRuleSet;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsExcludedFields {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsIdentifyingFields {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsIncludedFields {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsTableReference {
  dataset_id: string;
  project_id: string;
  table_id: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptions {
  rows_limit?: number;
  rows_limit_percent?: number;
  sample_method?: string;
  excluded_fields: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsExcludedFields;
  identifying_fields: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsIdentifyingFields;
  included_fields: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsIncludedFields;
  table_reference: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptionsTableReference;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigCloudStorageOptionsFileSetRegexFileSet {
  bucket_name: string;
  exclude_regex?: string[];
  include_regex?: string[];
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigCloudStorageOptionsFileSet {
  url?: string;
  regex_file_set: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigCloudStorageOptionsFileSetRegexFileSet;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigCloudStorageOptions {
  bytes_limit_per_file?: number;
  bytes_limit_per_file_percent?: number;
  file_types?: string[];
  files_limit_percent?: number;
  sample_method?: string;
  file_set: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigCloudStorageOptionsFileSet;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigDatastoreOptionskind {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigDatastoreOptionsPartitionId {
  namespace_id?: string;
  project_id: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigDatastoreOptions {
  kind: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigDatastoreOptionskind;
  partition_id: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigDatastoreOptionsPartitionId;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigHybridOptionsTableOptionsIdentifyingFields {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigHybridOptionsTableOptions {
  identifying_fields: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigHybridOptionsTableOptionsIdentifyingFields;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigHybridOptions {
  description?: string;
  labels?: {
    [key: string]: string;
  };
  required_finding_label_keys?: string[];
  table_options: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigHybridOptionsTableOptions;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigTimespanConfigTimestampField {
  name: string;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigTimespanConfig {
  enable_auto_population_of_timespan_config?: boolean;
  end_time?: string;
  start_time?: string;
  timestamp_field: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigTimespanConfigTimestampField;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfig {
  big_query_options: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigBigQueryOptions;
  cloud_storage_options: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigCloudStorageOptions;
  datastore_options: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigDatastoreOptions;
  hybrid_options: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigHybridOptions;
  timespan_config: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfigTimespanConfig;
}
export interface GoogleDataLossPreventionJobTriggerArgsInspectJob {
  inspect_template_name?: string;
  actions: GoogleDataLossPreventionJobTriggerArgsInspectJobactions;
  inspect_config: GoogleDataLossPreventionJobTriggerArgsInspectJobInspectConfig;
  storage_config: GoogleDataLossPreventionJobTriggerArgsInspectJobStorageConfig;
}
export interface GoogleDataLossPreventionJobTriggerArgstimeouts {
  create?: string;
  delete?: string;
  update?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgstriggersmanual {}
export interface GoogleDataLossPreventionJobTriggerArgstriggersschedule {
  recurrence_period_duration?: string;
}
export interface GoogleDataLossPreventionJobTriggerArgstriggers {
  manual: GoogleDataLossPreventionJobTriggerArgstriggersmanual;
  schedule: GoogleDataLossPreventionJobTriggerArgstriggersschedule;
}
export interface GoogleDataLossPreventionJobTriggerArgs {
  description?: string;
  display_name?: string;
  parent: string;
  status?: string;
  inspect_job: GoogleDataLossPreventionJobTriggerArgsInspectJob;
  timeouts: GoogleDataLossPreventionJobTriggerArgstimeouts;
  triggers: GoogleDataLossPreventionJobTriggerArgstriggers;
}
export class google_data_loss_prevention_job_trigger extends TerraformResource {
  readonly create_time!: string;
  readonly id?: string;
  readonly last_run_time!: string;
  readonly name!: string;
  readonly trigger_id?: string;
  readonly update_time!: string;
  constructor(config: TerraformConfig, resourceName: string, args: GoogleDataLossPreventionJobTriggerArgs) {
    super(config, "resource", args, resourceName, "google_data_loss_prevention_job_trigger");
  }
}