import { TerraformConfig, TerraformResource } from "tfs";
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesdictionaryCloudStoragePath {
  path: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesdictionaryWordList {
  words: string[];
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesdictionary {
  cloud_storage_path: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesdictionaryCloudStoragePath;
  word_list: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesdictionaryWordList;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesInfoType {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesregex {
  group_indexes?: number[];
  pattern: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesStoredType {
  name: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesSurrogateType {}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypes {
  exclusion_type?: string;
  likelihood?: string;
  dictionary: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesdictionary;
  info_type: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesInfoType;
  regex: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesregex;
  sensitivity_score: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesSensitivityScore;
  stored_type: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesStoredType;
  surrogate_type: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypesSurrogateType;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionInspectTemplateArgsInspectConfigInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimitsMaxFindingsPerInfoTypeInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimitsMaxFindingsPerInfoTypeInfoType {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimitsMaxFindingsPerInfoTypeInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimitsMaxFindingsPerInfoType {
  max_findings: number;
  info_type: GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimitsMaxFindingsPerInfoTypeInfoType;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimits {
  max_findings_per_item: number;
  max_findings_per_request: number;
  max_findings_per_info_type: GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimitsMaxFindingsPerInfoType;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuledictionaryCloudStoragePath {
  path: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuledictionaryWordList {
  words: string[];
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuledictionary {
  cloud_storage_path: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuledictionaryCloudStoragePath;
  word_list: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuledictionaryWordList;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordHotwordRegex {
  group_indexes?: number[];
  pattern: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordproximity {
  window_after?: number;
  window_before?: number;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeByHotword {
  hotword_regex: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordHotwordRegex;
  proximity: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeByHotwordproximity;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypes {
  info_types: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypesInfoTypes;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleregex {
  group_indexes?: number[];
  pattern: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRule {
  matching_type: string;
  dictionary: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuledictionary;
  exclude_by_hotword: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeByHotword;
  exclude_info_types: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleExcludeInfoTypes;
  regex: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRuleregex;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRuleHotwordRegex {
  group_indexes?: number[];
  pattern: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRuleLikelihoodAdjustment {
  fixed_likelihood?: string;
  relative_likelihood?: number;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRuleproximity {
  window_after?: number;
  window_before?: number;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRule {
  hotword_regex: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRuleHotwordRegex;
  likelihood_adjustment: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRuleLikelihoodAdjustment;
  proximity: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRuleproximity;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrules {
  exclusion_rule: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesExclusionRule;
  hotword_rule: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrulesHotwordRule;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSet {
  info_types: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetInfoTypes;
  rules: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSetrules;
}
export interface GoogleDataLossPreventionInspectTemplateArgsInspectConfig {
  content_options?: string[];
  exclude_info_types?: boolean;
  include_quote?: boolean;
  min_likelihood?: string;
  custom_info_types: GoogleDataLossPreventionInspectTemplateArgsInspectConfigCustomInfoTypes;
  info_types: GoogleDataLossPreventionInspectTemplateArgsInspectConfigInfoTypes;
  limits: GoogleDataLossPreventionInspectTemplateArgsInspectConfiglimits;
  rule_set: GoogleDataLossPreventionInspectTemplateArgsInspectConfigRuleSet;
}
export interface GoogleDataLossPreventionInspectTemplateArgstimeouts {
  create?: string;
  delete?: string;
  update?: string;
}
export interface GoogleDataLossPreventionInspectTemplateArgs {
  description?: string;
  display_name?: string;
  parent: string;
  inspect_config: GoogleDataLossPreventionInspectTemplateArgsInspectConfig;
  timeouts: GoogleDataLossPreventionInspectTemplateArgstimeouts;
}
export class google_data_loss_prevention_inspect_template extends TerraformResource {
  readonly id?: string;
  readonly name!: string;
  readonly template_id?: string;
  constructor(config: TerraformConfig, resourceName: string, args: GoogleDataLossPreventionInspectTemplateArgs) {
    super(config, "resource", args, resourceName, "google_data_loss_prevention_inspect_template");
  }
}