import { TerraformConfig, TerraformResource } from "tfs";
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsAllInfoTypes {}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsAllText {}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsRedactionColor {
  blue?: number;
  green?: number;
  red?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsSelectedInfoTypesInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsSelectedInfoTypesInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsSelectedInfoTypesInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsSelectedInfoTypes {
  info_types: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsSelectedInfoTypesInfoTypes;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransforms {
  all_info_types: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsAllInfoTypes;
  all_text: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsAllText;
  redaction_color: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsRedactionColor;
  selected_info_types: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransformsSelectedInfoTypes;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformations {
  transforms: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationstransforms;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmax {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmin {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValue {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbuckets {
  max: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmax;
  min: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmin;
  replacement_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfig {
  buckets: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbuckets;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore {
  characters_to_skip?: string;
  common_characters_to_ignore?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfig {
  masking_character?: string;
  number_to_mask?: number;
  reverse_order?: boolean;
  characters_to_ignore: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigcontext {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfig {
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfig {
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKey;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigcontext {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig {
  common_alphabet?: string;
  custom_alphabet?: string;
  radix?: number;
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigcontext {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfig {
  lower_bound_days: number;
  upper_bound_days: number;
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKey;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound {
  float_value?: number;
  integer_value?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound {
  float_value?: number;
  integer_value?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfig {
  bucket_size: number;
  lower_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound;
  upper_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationRedactConfig {}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: number;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfig {
  new_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfigWordList {
  words: string[];
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfig {
  word_list: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfigWordList;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationTimePartConfig {
  part_to_extract?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformation {
  replace_with_info_type_config?: boolean;
  bucketing_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfig;
  character_mask_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfig;
  crypto_deterministic_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfig;
  crypto_hash_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfig;
  crypto_replace_ffx_fpe_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig;
  date_shift_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfig;
  fixed_size_bucketing_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfig;
  redact_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationRedactConfig;
  replace_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfig;
  replace_dictionary_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfig;
  time_part_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformationTimePartConfig;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformations {
  info_types: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsInfoTypes;
  primitive_transformation: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformationsPrimitiveTransformation;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformations {
  transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationstransformations;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsfield {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsvalueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsvalueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsvalue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsvalueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsvalueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditions {
  operator: string;
  field: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsfield;
  value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditionsvalue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditions {
  conditions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditionsconditions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressions {
  logical_operator?: string;
  conditions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressionsconditions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationscondition {
  expressions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsconditionexpressions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsfields {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsInfoTypesSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsInfoTypes {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsInfoTypesSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmax {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmaxTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmin {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsminTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValue {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbuckets {
  max: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmax;
  min: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsmin;
  replacement_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfig {
  buckets: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfigbuckets;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore {
  characters_to_skip?: string;
  common_characters_to_ignore?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfig {
  masking_character?: string;
  number_to_mask?: number;
  reverse_order?: boolean;
  characters_to_ignore: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigcontext {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfig {
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfig {
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfigCryptoKey;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigcontext {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType {
  name: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig {
  common_alphabet?: string;
  custom_alphabet?: string;
  radix?: number;
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigcontext {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfig {
  lower_bound_days: number;
  upper_bound_days: number;
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfigCryptoKey;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound {
  float_value?: number;
  integer_value?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound {
  float_value?: number;
  integer_value?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfig {
  bucket_size: number;
  lower_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound;
  upper_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationRedactConfig {}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfig {
  new_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfigNewValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfigWordList {
  words: string[];
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfig {
  word_list: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfigWordList;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceWithInfoTypeConfig {}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationTimePartConfig {
  part_to_extract: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformation {
  bucketing_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationBucketingConfig;
  character_mask_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCharacterMaskConfig;
  crypto_deterministic_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoDeterministicConfig;
  crypto_hash_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoHashConfig;
  crypto_replace_ffx_fpe_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig;
  date_shift_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationDateShiftConfig;
  fixed_size_bucketing_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationFixedSizeBucketingConfig;
  redact_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationRedactConfig;
  replace_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceConfig;
  replace_dictionary_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceDictionaryConfig;
  replace_with_info_type_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationReplaceWithInfoTypeConfig;
  time_part_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformationTimePartConfig;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformations {
  info_types: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsInfoTypes;
  primitive_transformation: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformationsPrimitiveTransformation;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformations {
  transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationstransformations;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmaxDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmaxTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmax {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmaxDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmaxTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsminDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsminTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmin {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsminDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsminTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbuckets {
  max: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmax;
  min: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsmin;
  replacement_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbucketsReplacementValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfig {
  buckets: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigbuckets;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore {
  characters_to_skip?: string;
  common_characters_to_ignore?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfig {
  masking_character?: string;
  number_to_mask?: number;
  reverse_order?: boolean;
  characters_to_ignore: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigcontext {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfig {
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfig {
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigcontext {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig {
  common_alphabet?: string;
  custom_alphabet?: string;
  radix?: number;
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigcontext {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeytransient {
  name: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyunwrapped {
  key: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKey {
  kms_wrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped;
  transient: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeytransient;
  unwrapped: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyunwrapped;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfig {
  lower_bound_days: number;
  upper_bound_days: number;
  context: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigcontext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKey;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfig {
  bucket_size: number;
  lower_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound;
  upper_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationRedactConfig {}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfig {
  new_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList {
  words: string[];
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfig {
  word_list: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationTimePartConfig {
  part_to_extract?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformation {
  bucketing_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfig;
  character_mask_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfig;
  crypto_deterministic_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfig;
  crypto_hash_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfig;
  crypto_replace_ffx_fpe_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig;
  date_shift_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfig;
  fixed_size_bucketing_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfig;
  redact_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationRedactConfig;
  replace_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfig;
  replace_dictionary_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfig;
  time_part_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationTimePartConfig;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformations {
  condition: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationscondition;
  fields: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsfields;
  info_type_transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformations;
  primitive_transformation: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformation;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsfield {
  name?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsvalueDateValue {
  day?: number;
  month?: number;
  year?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsvalueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsvalue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsvalueDateValue;
  time_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsvalueTimeValue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditions {
  operator: string;
  field: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsfield;
  value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditionsvalue;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditions {
  conditions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditionsconditions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressions {
  logical_operator?: string;
  conditions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressionsconditions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionscondition {
  expressions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsconditionexpressions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressions {
  condition: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionscondition;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformations {
  field_transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformations;
  record_suppressions: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressions;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfig {
  image_transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformations;
  info_type_transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformations;
  record_transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformations;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgstimeouts {
  create?: string;
  delete?: string;
  update?: string;
}
export interface GoogleDataLossPreventionDeidentifyTemplateArgs {
  description?: string;
  display_name?: string;
  parent: string;
  deidentify_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfig;
  timeouts: GoogleDataLossPreventionDeidentifyTemplateArgstimeouts;
}
export class google_data_loss_prevention_deidentify_template extends TerraformResource {
  readonly create_time!: string;
  readonly id?: string;
  readonly name!: string;
  readonly template_id?: string;
  readonly update_time!: string;
  constructor(config: TerraformConfig, resourceName: string, args: GoogleDataLossPreventionDeidentifyTemplateArgs) {
    super(config, "resource", args, resourceName, "google_data_loss_prevention_deidentify_template");
  }
}