import { TerraformConfig, TerraformResource } from "tfs";
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsExportDataProfileTable {
  dataset_id?: string;
  project_id?: string;
  table_id?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsExportData {
  profile_table: GoogleDataLossPreventionDiscoveryConfigArgsactionsExportDataProfileTable;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotificationPubsubConditionexpressionsconditions {
  minimum_risk_score?: string;
  minimum_sensitivity_score?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotificationPubsubConditionexpressions {
  logical_operator?: string;
  conditions: GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotificationPubsubConditionexpressionsconditions;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotificationPubsubCondition {
  expressions: GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotificationPubsubConditionexpressions;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotification {
  detail_of_message?: string;
  event?: string;
  topic?: string;
  pubsub_condition: GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotificationPubsubCondition;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResourcesTagConditionsSensitivityScore {
  score: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResourcesTagConditionstag {
  namespaced_value?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResourcesTagConditions {
  sensitivity_score: GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResourcesTagConditionsSensitivityScore;
  tag: GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResourcesTagConditionstag;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResources {
  lower_data_risk_to_low?: boolean;
  profile_generations_to_tag?: string[];
  tag_conditions: GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResourcesTagConditions;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsactions {
  export_data: GoogleDataLossPreventionDiscoveryConfigArgsactionsExportData;
  pub_sub_notification: GoogleDataLossPreventionDiscoveryConfigArgsactionsPubSubNotification;
  tag_resources: GoogleDataLossPreventionDiscoveryConfigArgsactionsTagResources;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsOrgConfiglocation {
  folder_id?: string;
  organization_id?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgsOrgConfig {
  project_id?: string;
  location: GoogleDataLossPreventionDiscoveryConfigArgsOrgConfiglocation;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadenceInspectTemplateModifiedCadence {
  frequency?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadenceSchemaModifiedCadence {
  frequency?: string;
  types?: string[];
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadenceTableModifiedCadence {
  frequency?: string;
  types?: string[];
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadence {
  inspect_template_modified_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadenceInspectTemplateModifiedCadence;
  schema_modified_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadenceSchemaModifiedCadence;
  table_modified_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadenceTableModifiedCadence;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetconditionsOrConditions {
  min_age?: string;
  min_row_count?: number;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetconditionstypes {
  types?: string[];
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetconditions {
  created_after?: string;
  type_collection?: string;
  or_conditions: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetconditionsOrConditions;
  types: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetconditionstypes;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetdisabled {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfilterOtherTables {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfilterTableReference {
  dataset_id: string;
  table_id: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfiltertablesIncludeRegexespatterns {
  dataset_id_regex?: string;
  project_id_regex?: string;
  table_id_regex?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfiltertablesIncludeRegexes {
  patterns: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfiltertablesIncludeRegexespatterns;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfiltertables {
  include_regexes: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfiltertablesIncludeRegexes;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfilter {
  other_tables: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfilterOtherTables;
  table_reference: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfilterTableReference;
  tables: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfiltertables;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTarget {
  cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetcadence;
  conditions: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetconditions;
  disabled: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetdisabled;
  filter: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTargetfilter;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetconditions {
  database_engines?: string[];
  types?: string[];
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetdisabled {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfiltercollectionIncludeRegexespatterns {
  database_regex?: string;
  database_resource_name_regex?: string;
  instance_regex?: string;
  project_id_regex?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfiltercollectionIncludeRegexes {
  patterns: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfiltercollectionIncludeRegexespatterns;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfiltercollection {
  include_regexes: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfiltercollectionIncludeRegexes;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfilterDatabaseResourceReference {
  database: string;
  database_resource: string;
  instance: string;
  project_id: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfilterothers {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfilter {
  collection: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfiltercollection;
  database_resource_reference: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfilterDatabaseResourceReference;
  others: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfilterothers;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetGenerationCadenceInspectTemplateModifiedCadence {
  frequency: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetGenerationCadenceSchemaModifiedCadence {
  frequency?: string;
  types?: string[];
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetGenerationCadence {
  refresh_frequency?: string;
  inspect_template_modified_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetGenerationCadenceInspectTemplateModifiedCadence;
  schema_modified_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetGenerationCadenceSchemaModifiedCadence;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTarget {
  conditions: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetconditions;
  disabled: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetdisabled;
  filter: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetfilter;
  generation_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTargetGenerationCadence;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetconditionsCloudStorageConditions {
  included_bucket_attributes?: string[];
  included_object_attributes?: string[];
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetconditions {
  created_after?: string;
  min_age?: string;
  cloud_storage_conditions: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetconditionsCloudStorageConditions;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetdisabled {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfilterCloudStorageResourceReference {
  bucket_name?: string;
  project_id?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollectionIncludeRegexespatternsCloudStorageRegex {
  bucket_name_regex?: string;
  project_id_regex?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollectionIncludeRegexespatterns {
  cloud_storage_regex: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollectionIncludeRegexespatternsCloudStorageRegex;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollectionIncludeRegexes {
  patterns: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollectionIncludeRegexespatterns;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollection {
  include_regexes: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollectionIncludeRegexes;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfilterothers {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfilter {
  cloud_storage_resource_reference: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfilterCloudStorageResourceReference;
  collection: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfiltercollection;
  others: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfilterothers;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetGenerationCadenceInspectTemplateModifiedCadence {
  frequency?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetGenerationCadence {
  refresh_frequency?: string;
  inspect_template_modified_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetGenerationCadenceInspectTemplateModifiedCadence;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTarget {
  conditions: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetconditions;
  disabled: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetdisabled;
  filter: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetfilter;
  generation_cadence: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTargetGenerationCadence;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargetsSecretsTarget {}
export interface GoogleDataLossPreventionDiscoveryConfigArgstargets {
  big_query_target: GoogleDataLossPreventionDiscoveryConfigArgstargetsBigQueryTarget;
  cloud_sql_target: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudSqlTarget;
  cloud_storage_target: GoogleDataLossPreventionDiscoveryConfigArgstargetsCloudStorageTarget;
  secrets_target: GoogleDataLossPreventionDiscoveryConfigArgstargetsSecretsTarget;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgstimeouts {
  create?: string;
  delete?: string;
  update?: string;
}
export interface GoogleDataLossPreventionDiscoveryConfigArgs {
  display_name?: string;
  inspect_templates?: string[];
  location: string;
  parent: string;
  status?: string;
  actions: GoogleDataLossPreventionDiscoveryConfigArgsactions;
  org_config: GoogleDataLossPreventionDiscoveryConfigArgsOrgConfig;
  targets: GoogleDataLossPreventionDiscoveryConfigArgstargets;
  timeouts: GoogleDataLossPreventionDiscoveryConfigArgstimeouts;
}
export class google_data_loss_prevention_discovery_config extends TerraformResource {
  readonly create_time!: string;
  readonly errors!: any[];
  readonly id?: string;
  readonly last_run_time!: string;
  readonly name!: string;
  readonly update_time!: string;
  constructor(config: TerraformConfig, resourceName: string, args: GoogleDataLossPreventionDiscoveryConfigArgs) {
    super(config, "resource", args, resourceName, "google_data_loss_prevention_discovery_config");
  }
}